[package]
name = "cityjson-export"
version = "0.1.0"
edition = "2021"
authors = ["Balázs Dukai <balazs.dukai@3dgi.nl>", "Ravi Peters <ravi.peters@3dgi.nl>"]
description = "CityJSON format conversion utilities."
license = "Apache-2.0"

[[bin]]
name = "cjexport"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
bincode = "1.3.3"
bitvec = "1.0.1"
cityjson-index = "0.3.1"
cityjson-lib = "0.5.2"
clap = { version = "4.0.32", features = ["cargo", "derive"] }
earcutr = "0.2"
env_logger = "0.10.0"
gltf = "1.4"
libc = "0.2.119"
log = "0.4.17"
morton-encoding = "2.0.1"
num-traits = "0.2.14"
rayon = "1.6.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
serde_repr = "0.1.10"
thiserror = "1.0.30"
walkdir = "2.3.2"

# crates needed for the proj adaptation
proj-sys = { version = "0.23.1", path = "../proj/proj-sys", features = ["network"] }
