[workspace]
resolver = "2"

[package]
name = "cityjson-convert-gis-integration"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = "1"
cityjson-convert = { path = "../..", default-features = false, features = ["proj-system"] }
cityjson-lib = { version = "0.10.0", default-features = false }
tempfile = "3"

[patch.crates-io]
cityjson-lib = { git = "https://github.com/3DGI/cityjson-rs.git", rev = "af1b4795b5e589ac8017fab54fbe6b9068ee2ef3" }
cityjson-index = { git = "https://github.com/3DGI/cityjson-rs.git", rev = "af1b4795b5e589ac8017fab54fbe6b9068ee2ef3" }
cityjson-types = { git = "https://github.com/3DGI/cityjson-rs.git", rev = "af1b4795b5e589ac8017fab54fbe6b9068ee2ef3" }
cityjson-json = { git = "https://github.com/3DGI/cityjson-rs.git", rev = "af1b4795b5e589ac8017fab54fbe6b9068ee2ef3" }
